[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/"
  to = "https://gosocial.io"
  force = true

[[redirects]]
  from = "/blog"
  to = "https://blog.gosocial.io"
  force = true

[[redirects]]
  from = "/privacy-policy.html"
  to = "https://about.gosocial.io/privacy-policy.html"
  force = true

[[redirects]]
  from = "/terms.html"
  to = "https://about.gosocial.io/terms.html"
  force = true

[[redirects]]
  from = "/gosocial-challenge-contributors"
  to = "https://about.gosocial.io/contributors"
  force = true

  
[[redirects]]  
  from = "/2019-12-26-host-your-own-photography-challenges-on-gosocial"  
  to = "https://blog.gosocial.io/host-your-own-photography-challenges-on-gosocial"  
  force = true

[[redirects]]  
  from = "/2019-11-28-introducing-gosocial"  
  to = "https://blog.gosocial.io/introducing-gosocial"  
  force = true
 
[[redirects]]  
  from = "/2020-07-10-5-common-mistakes-new-artists-make-how-to-avoid-them"  
  to = "https://blog.gosocial.io/common-mistakes-new-artists-make-how-to-avoid-them"  
  force = true
  
[[redirects]]  
  from = "/8-writing-challenges-to-boost-your-creativity"  
  to = "https://blog.gosocial.io/8-writing-challenges-to-boost-your-creativity"  
  force = true

 [[redirects]]  
  from = "/2020-07-20-6-ways-to-be-a-more-productive-artist"  
  to = "https://blog.gosocial.io/ways-to-be-a-more-productive-artist"  
  force = true
  
 [[redirects]]  
  from = "/2019-12-26-host-your-own-photography-contest-giveaway-on-gosocial"  
  to = "https://blog.gosocial.io/host-your-own-photography-contest-giveaway-on-gosocial"  
  force = true

[[redirects]]  
  from = "/2019-12-18-flip-your-photos-on-gosocial"  
  to = "https://blog.gosocial.io/host-your-own-photography-contest-giveaway-on-gosocial"  
  force = true

[[redirects]]  
  from = "/6-ways-to-make-money-as-an-artist"  
  to = "https://blog.gosocial.io/6-ways-to-make-money-as-an-artist"  
  force = true

[[redirects]]  
  from = "/2020-07-13-10-creative-photography-challenges-that-you-must-try"  
  to = "https://blog.gosocial.io/creative-photography-challenges-that-you-must-try"  
  force = true

[[redirects]]  
  from = "/8-tips-to-master-travel-photography"  
  to = "https://blog.gosocial.io/8-tips-to-master-travel-photography"  
  force = true

[[redirects]]  
  from = "/7-best-social-media-platforms-for-artists"  
  to = "https://blog.gosocial.io/7-best-social-media-platforms-for-artists"  
  force = true

[[redirects]]  
  from = "/2020-07-10-10-creative-art-challenges-to-try"  
  to = "https://blog.gosocial.io/creative-art-challenges-to-try"  
  force = true

[[redirects]]  
  from = "/how-to-write-a-horror-story-in-5-steps"
  to = "https://blog.gosocial.io/how-to-write-a-horror-story-in-5-steps"  
  force = true

[[redirects]]  
  from = "/2019-12-19-gosocial-introducing-creative-challenges-designed-by-experts"
  to = "https://blog.gosocial.io/gosocial-introducing-creative-challenges-designed-by-experts"  
  force = true
  
[[redirects]]  
  from = "/kickstart-your-learning-with-these-5-photography-challenges-for-beginners"
  to = "https://blog.gosocial.io/kickstart-your-learning-with-these-5-photography-challenges-for-beginners"  
  force = true
  
[[redirects]]  
  from = "/2020-07-16-how-to-improve-writing-skills-in-7-easy-steps"
  to = "https://blog.gosocial.io/how-to-improve-writing-skills-in-7-easy-steps"  
  force = true
  
[[redirects]]  
  from = "/gosocial-the-go-to-app-for-photographers"
  to = "https://blog.gosocial.io/gosocial-the-go-to-app-for-photographers"  
  force = true
  
[[redirects]]  
  from = "/get-your-house-ready-for-great-diwali-photos"
  to = "https://blog.gosocial.io/get-your-house-ready-for-great-diwali-photos"  
  force = true
  
[[redirects]]  
  from = "/2020-01-22-ultimate-guide-to-get-started-with-photography"
  to = "https://blog.gosocial.io/ultimate-guide-to-get-started-with-photography"  
  force = true
  
[[redirects]]  
  from = "/2020-02-06-how-to-learn-photography-online"
  to = "https://blog.gosocial.io/how-to-learn-photography-online"  
  force = true

[[redirects]]  
  from = "/2020-07-06-Watercolor-Mandalas-Art-Challenge"  
  to = "https://gosocial.io/challenge/watercolor-mandalas-art-challenge"  
  force = true

[[redirects]]  
  from = "/2020-07-22-Recreate-Nature-Art-Challenge"  
  to = "https://gosocial.io/challenge/recreate-nature-art-challenge/"  
  force = true

[[redirects]]  
  from = "/2020-05-22-Freewriting-Poetry-Challenge"  
  to = "https://gosocial.io/challenge/freewriting-poetry-challenge"  
  force = true

[[redirects]]  
  from = "/2020-06-18-nazm-e-quarantine-or-writing-challenge"  
  to = "https://gosocial.io/challenge/nazm-e-quarantine-writing-challenge"  
  force = true

[[redirects]]  
  from = "/2020-05-04-My-Todays-Outfit-Self-portrait-Challenge"  
  to = "https://gosocial.io/challenge/my-todays-outfit-self-portrait-challenge"  
  force = true

[[redirects]]  
  from = "/2020-09-29-Object-Illustration-Art-Challenge"  
  to = "https://gosocial.io/challenge/object-illustration-art-challenge"  
  force = true

[[redirects]]  
  from = "/2020-07-23-poetry-on-hope-writing-challenge"  
  to = "https://gosocial.io/challenge/poetry-on-hope-writing-challenge"  
  force = true

[[redirects]]  
  from = "/2020-05-16-Watercolor-landscape-Art-Challenge"  
  to = "https://gosocial.io/challenge/watercolor-landscape-art-challenge"  
  force = true

[[redirects]]  
  from = "/2020-03-19-Document-Your-Lifestyle-Photography-Challenge"  
  to = "https://gosocial.io/challenge/document-your-lifestyle-photography-challenge"  
  force = true

[[redirects]]  
  from = "/2020-07-13-monochromes-art-challenge"
  to = "https://gosocial.io/challenge/monochromes-art-challenge"  
  force = true

[[redirects]]  
  from = "/2020-02-05-Tri-color-Photography-Challenge"
  to = "https://gosocial.io/challenge/tri-color-photography-challenge"  
  force = true

[[redirects]]  
  from = "/how-to-write-a-poem-in-7-steps.html
  to = "https://blog.gosocial.io/how-to-write-a-poem-in-7-steps/"  
  force = true

[[redirects]]  
  from = "/2020-06-30-fantasy-drawing-art-challenge"
  to = "https://gosocial.io/challenge/fantasy-drawing-art-challenge"  
  force = true

[[redirects]]  
  from = "/2020-06-19-Abstract-Art-Challenge"
  to = "https://gosocial.io/challenge/abstract-art-challenge"  
  force = true

[[redirects]]  
  from = "/2020-05-22-Poetry-Prompt-Sun-Shadows-Writing-Challenge"
  to = "https://gosocial.io/challenge/poetry-prompt-sunshadows-writing-challenge"  
  force = true

[[redirects]]  
  from = "/2020-05-22-finish-the-story-or-sci-fi-writing-challenge"
  to = "https://gosocial.io/challenge/finish-the-story-sci-fi-writing-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-04-18-Window-Silhouette-Photography-Challenge"
  to = "https://gosocial.io/challenge/window-silhouette-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-05-18-Tea-and-Storytelling-Photography-Challenge"
  to = "https://gosocial.io/challenge/tea-and-storytelling-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-11-03-SpreadKhushiya-Photography-Challenge"
  to = "https://gosocial.io/challenge/spreadkhushiya-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-06-02-1-Minute-Writing-Challenge"
  to = "https://gosocial.io/challenge/1-minute-writing-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-06-14-150-Character-Tale-on-Coffee
  to = "https://gosocial.io/challenge/150-character-tale-on-coffee"  
  force = true
  
[[redirects]]  
  from = "/2019-12-11-A-Memorable-Moment-Photography-Challenge"
  to = "https://gosocial.io/challenge/a-memorable-moment-photography-challenge"  
  force = true

[[redirects]]  
  from = "/2020-02-21-Beach-Photography-Challenge"
  to = "https://gosocial.io/challenge/beach-photography-challenge"  
  force = true

[[redirects]]  
  from = "/2020-07-22-cloudscapes-photography-challenge"
  to = "https://gosocial.io/challenge/cloudscapes-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-03-13-matchsticks-photography-challenge"
  to = "https://gosocial.io/challenge/matchsticks-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-01-13-fun-fair-photography-challenge"
  to = "https://gosocial.io/challenge/fun-fair-photography-challenge"  
  force = true
    
[[redirects]]  
  from = "/2020-06-08-The-Half-Chakra-Mandala-Challenge"
  to = "https://gosocial.io/challenge/the-half-chakra-mandala-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-10-14-Watercolor-Flow-Art-Challenge"
  to = "https://gosocial.io/challenge/watercolor-flow-art-challenge"  
  force = true
    
[[redirects]]  
  from = "/2020-10-14-A-Memory-Writing-Challenge"
  to = "https://gosocial.io/challenge/a-memory-writing-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-07-06-dreams-writing-challenge"
  to = "https://gosocial.io/challenge/dreams-writing-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-00-16-outside-your-window-photo-challenge"
  to = "https://gosocial.io/challenge/outside-your-window-photo-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-10-14-Pastel-Mandala-Art-Challenge"
  to = "https://gosocial.io/challenge/pastel-mandala-art-challenge"  
  force = true
  


[[redirects]]  
  from = "/2020-04-13-Flat-Lay-Food-Photography-Challenge"
  to = "https://gosocial.io/challenge/flat-lay-food-photography-challenge"  
  force = true

[[redirects]]  
  from = "/2020-04-04-Flower-in-Ice-Frozen-Flower-Photography-Challenge"
  to = "https://gosocial.io/challenge/flower-in-ice-frozen-flower-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-08-17-Letter-To-Myself-in-Another-Universe-Writing-Challenge"
  to = "https://gosocial.io/challenge/letter-to-myself-in-another-universe-writing-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-02-12-Light-Painting-Photography-Challenge"
  to = "https://gosocial.io/challenge/light-painting-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-06-24-fashion-drawing-art-challenge"
  to = "https://gosocial.io/challenge/fashion-drawing-art-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-03-15-Funky-Portrait-photography-Challenge"
  to = "https://gosocial.io/challenge/funky-portrait-photography-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-05-21-Sketch-Dailiesâ€“-Daily-Sketching-Challenge"
  to = "https://gosocial.io/challenge/sketch-dailies-daily-sketching-challenge"  
  force = true
  
[[redirects]]  
  from = "/2020-06-15-Design-a-Tile-Art-Challenge"
  to = "https://gosocial.io/challenge/design-a-tile-art-challenge"  
  force = true

[[redirects]]
  from = "/*"
  to = "https://gosocial.io"
  force = true